### ISSUE TITLE
Cannot use model with `fit_atoms: True`

### ISSUE THREAD

**Issue by MaciejDzikowski** [mattragoza/LiGAN#62]
We are trying to use LiGAN and generate molecule-level metrics.  
In order to achieve that, atom fitting is required to be turned on. However, when the option is set on, the process is interrupted by: `KeyError: 'minimizedAffinity'`. Also, we are getting some *Open Babel* warnings, but I am not sure if it is relevant in this case.  
The error message:  
![lfit_atoms_err](https://user-images.githubusercontent.com/49808559/215190361-09d42028-941f-4e3e-ae35-eaf9385277db.png)

Sample of *PDB* files we are providing to model ([source](https://www.rcsb.org/structure/7rdz)) - *.csv* file fragment:
``` csv
0 0 0 7rdz.pdb 7rdz_J_ZN.sdf
0 0 0 7rdz.pdb 7rdz_K_MG.sdf
0 0 0 7rdz.pdb 7rdz_L_ADP.sdf
```

**Comment by mattragoza** [comment]
If you scroll up a bit in the output you see an error message from gnina: `Runtime Error an illegal memory access was encountered`. How did you install gnina?

**Comment by DomaradzkiMaciej** [comment]
Hi Matt, sorry for late reply. 
I installed gnina directly from the github according to step 2.

![image](https://user-images.githubusercontent.com/56363057/215327498-11309be2-a934-4feb-9655-8bd7edd7212e.png)

**Comment by MaciejDzikowski** [comment]
We decided to use exemplary files from *LiGAN* repository as an input:
- [`./data/crossdock2020/1A02_HUMAN_25_199_pep_0/1eez_A_rec.pdb`](https://github.com/mattragoza/LiGAN/blob/master/data/crossdock2020/1A02_HUMAN_25_199_pep_0/1eez_A_rec.pdb) and [`./data/crossdock2020/1A02_HUMAN_25_199_pep_0/1eez_A_rec_2gj6_3ib_lig_tt_min_0.sdf.gz`](https://github.com/mattragoza/LiGAN/blob/master/data/crossdock2020/1A02_HUMAN_25_199_pep_0/1eez_A_rec_2gj6_3ib_lig_tt_min_0.sdf.gz) (decompressed),
- [`./data/crossdock2020/AROK_MYCTU_1_176_0/1zyu_A_rec.pdb`](https://github.com/mattragoza/LiGAN/blob/master/data/crossdock2020/AROK_MYCTU_1_176_0/1zyu_A_rec.pdb) and [`./data/crossdock2020/AROK_MYCTU_1_176_0/1zyu_A_rec_2dft_adp_lig_tt_docked_0.sdf.gz`](https://github.com/mattragoza/LiGAN/blob/master/data/crossdock2020/AROK_MYCTU_1_176_0/1zyu_A_rec_2dft_adp_lig_tt_docked_0.sdf.gz) (decompressed).

We've got 9 files (receptor, 2x pocket, 6x ligand) but still, there is no trace of files with metrics. :/

Here's a screenshot with an error message from a command line:
![image](https://user-images.githubusercontent.com/49808559/215843448-2228257c-8d91-406a-a0db-2ee93d6b9e49.png)

and our `generate.config` file:
```
--- # new_atom_typing/generate/gen0_CVAE-1.6_1zyu_A_rec_0_1.0_1.0/generate.config
out_prefix: their_example
model_type: CVAE
random_seed: 0
verbose: True
device: cuda

data:
  data_root: test_this_stuff/their_example
  data_file: test_this_stuff/their_example/eg1_their_example.csv
  batch_size: 5
  rec_typer: oadc-1.0
  lig_typer: oadc-1.0
  use_rec_elems: True
  resolution: 0.5
  grid_size: 48
  shuffle: False
  random_rotation: True
  random_translation: 2.0
  diff_cond_transform: False
  diff_cond_structs: False

gen_model:
  n_filters: 28
  width_factor: 2
  n_levels: 4
  conv_per_level: 4
  kernel_size: 3
  relu_leak: 0.1
  batch_norm: 0
  spectral_norm: 1
  pool_type: a
  unpool_type: 'n'
  pool_factor: 2
  n_latent: 128
  init_conv_pool: 0
  skip_connect: True
  block_type: r
  growth_rate: 0
  bottleneck_factor: 0
  state: weights/train6_CVAE2_0_p0_4.0_4.0_k200_d_1.6_r0_n_4.0_65_iter_1000000.gen_model_state

atom_fitting:
  beam_size: 1
  multi_atom: False
  n_atoms_detect: 1
  apply_conv: False
  threshold: 0.1
  peak_value: 1.5
  min_dist: 0.0
  apply_prop_conv: False
  interm_gd_iters: 10
  final_gd_iters: 100

generate:
  n_examples: 1
  n_samples: 1
  prior: False
  var_factor: 1.0
  post_factor: 1.0
  stage2: False
  truncate: False
  interpolate: False
  spherical: False
  fit_atoms: True
  add_bonds: True
  uff_minimize: True
  gnina_minimize: True
  minimize_real: True

output:
  batch_metrics: False
  output_grids: False
  output_structs: False
  output_mols: True
  output_latents: True
  output_visited: False
  output_conv: False
```
